### ISSUE TITLE
ERROR: Unknown token when using marti -writeconfig

### ISSUE THREAD

**Issue by leiste375** [richardmleggett/MARTi#3]
Hi all

I recently set up MARTi (v0.9.16c) on a new system. When using the -writeconfig option to generate a new config file, using the updated marti_engine_options.txt from bin, I received the following error:

ERROR: Unknown token in marti_engine_options Kraken2Process
       Token is being ignored
ERROR: Unknown token in marti_engine_options       Name
       Token is being ignored
ERROR: Unknown token in marti_engine_options       Database
       Token is being ignored
ERROR: Unknown token in marti_engine_options       Kraken2Threads
       Token is being ignored
ERROR: Unknown token in marti_engine_options       UseToClassify
       Token is being ignored
Error: missing Centrifuge name.

I'm happy to look at it myself, as I assume it's only a minor error, but can't yet tell when I'll find time to do so.

**Comment by richardmleggett** [comment]
Sorry about this and thanks for reporting. We'll take a look...

**Comment by SR-Martin** [comment]
Fixed in 20f0c1d.
Centrifuge and Kraken2 processes will be recognised by -writeConfig and can be specified on the command line using the -centrifuge and -kraken2 options (in an analogous way to blast processes).

I also changed the error message to say "Warning", and fixed some weird formatting in marti_engine_options.txt that caused the final error message.
